#!/bin/bash

set -ex
REGISTRY="302062960021.dkr.ecr.us-east-1.amazonaws.com"
IMAGE_NAME="wanderinglabs/scraper-reserve_ca"
TAG="${1}"

docker build -t ${REGISTRY}/${IMAGE_NAME}:${TAG} -t ${REGISTRY}/${IMAGE_NAME}:latest .
docker push ${REGISTRY}/${IMAGE_NAME}:latest
