AllCops:
  Exclude:
    - 'db/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20 # Default: 15
Metrics/MethodLength:
  Max: 25 # Default: 10
Metrics/BlockLength:
  CountComments: true # count full line comments?
  Max: 25
  ExcludedMethods: []
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 120
Metrics/CyclomaticComplexity:
  Max: 12 # Default: 6
Metrics/PerceivedComplexity:
  Max: 14 # Default: 7

Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - 'spec/**/*.rb'
Style/ClassAndModuleChildren:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/**/*.rb'
Style/SingleLineBlockParams:
  Enabled: false
